### ISSUE TITLE
Padding is needed at the bottom of new trip page

### ISSUE THREAD

**Issue by mau-fyi** [sbahaud/summer-2022-team36#50]
On the new trip page it's difficult to read the bottom because it's so close to the end of the page.

![image](https://user-images.githubusercontent.com/79354255/179381458-32569ef6-029f-482c-bcf1-19e443ef0441.png)

**Comment by xiaoalem** [comment]
Fixed, in PR #51

**Comment by xiaoalem** [comment]
Moved the response message to the top with red color
